use_frameworks!

platform :ios, '9.0'

#DoKit检测工具
def pod_debug_kit
  pod 'WIKit'
end

target 'WILog_Example' do
  pod 'WILog', :path => '../'
  pod_debug_kit
  
  target 'WILog_Tests' do
    inherit! :search_paths

    
  end
end
