use_frameworks!

platform :ios, '9.0'

#DoKit检测工具
def pod_debug_kit
  pod 'DoraemonKit/Core', '~> 3.1.2'#, :configurations => ['Debug'] #必选
  pod 'DoraemonKit/WithLogger', '~> 3.1.2'#, :configurations => ['Debug'] #可选
  #pod 'DoraemonKit/WithDatabase', '~> 3.1.2'#, :configurations => ['Debug'] #可选
end

target 'WILog_Example' do
  pod 'WILog', :path => '../'
  pod_debug_kit
  
  target 'WILog_Tests' do
    inherit! :search_paths

    
  end
end
